---
description: Request a change to an existing option
labels: ["kind: change-option"]
name: Change option
title: "<SCOPE>: <DESCRIPTION>"

body:
  - type: textarea

    attributes:
      label: Description

      description: >-
        Describe the change and its potential breaking changes, and demonstrate
        the use case it improves.

      placeholder: Type your description here…

    validations:
      required: true

  - type: checkboxes

    attributes:
      label: Submission Checklist

      options:
        - label: I assert that this issue is relevant to Stylix
          required: true

        - label: >-
            I assert that this is not a duplicate of an [existing
            issue](https://github.com/nix-community/stylix/issues?q=is%3Aissue)

          required: true

  - type: textarea

    attributes:
      label: Notify maintainers

      description: >-
        Consider pinging the module maintainers. Each module lists its
        maintainers in the
        [documentation](https://nix-community.github.io/stylix).

      placeholder: "@awwpotato @danth @trueNAHO"
