---
description: Request the addition of a new option
labels: ["kind: new-option"]
name: New option
title: "<SCOPE>: add <OPTION> option"

body:
  - type: textarea

    attributes:
      label: Description

      description: >-
        Describe the option and explain its use case. Consider including
        pseudocode demonstrating its integration with the existing architecture.

      placeholder: Type your description here…

    validations:
      required: true

  - type: checkboxes

    attributes:
      label: Submission Checklist

      options:
        - label: I assert that this issue is relevant to Stylix
          required: true

        - label: >-
            I assert that this is not a duplicate of an [existing
            issue](https://github.com/nix-community/stylix/issues?q=is%3Aissue)

          required: true

  - type: textarea

    attributes:
      label: Notify maintainers

      description: >-
        Consider pinging the module maintainers. Each module lists its
        maintainers in the
        [documentation](https://nix-community.github.io/stylix).

      placeholder: "@awwpotato @danth @trueNAHO"
