---
description: Request the addition of a new target
labels: ["kind: new-target"]
name: New target
title: "<TARGET>: add target"

body:
  - type: textarea

    attributes:
      label: Description

      description: >-
        Describe the feature. Consider including links to existing themes, like
        a [tinted-theming repository](https://github.com/tinted-theming).

      placeholder: Type your description here…

    validations:
      required: true

  - type: checkboxes

    attributes:
      label: Submission Checklist

      options:
        - label: I assert that this issue is relevant to Stylix
          required: true

        - label: >-
            I assert that this is not a duplicate of an [existing
            issue](https://github.com/nix-community/stylix/issues?q=is%3Aissue)

          required: true
