---
name: Check

on:
  push:
    branches:
      - master
      - release-**
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    # https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#choosing-github-hosted-runners
    strategy:
      matrix:
        include:
          - name: aarch64-linux
            runs-on: ubuntu-24.04-arm
          - name: aarch64-darwin
            runs-on: macos-15
          - name: x86_64-linux
            runs-on: ubuntu-24.04
          - name: x86_64-darwin
            runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@v31

      - run: nix build .#get-maintainers

      # - uses: cachix/cachix-action@v16
      #   with:
      #     name: stylix
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      #   continue-on-error: true

      - id: get-maintainers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # MAX_MAINTAINERS: 5
          # PR_NUMBER: ${{ github.event.pull_request.number }}
          MAX_MAINTAINERS: 999
          PR_NUMBER: "1642"
        run: |
          printf \
            'reviewers=%s\n' \
            "$(
              gh pr diff --name-only "$PR_NUMBER" |
                jq \
                  --argjson max_maintainers "$MAX_MAINTAINERS" \
                  --raw-input \
                  --raw-output \
                  --slurp \
                  --slurpfile maintainers result '
                    ($maintainers[0] | keys_unsorted) as $subsystems |
                    split("\n") as $changed_files |
                    [
                      $changed_files[] as $changed_file |
                      (
                        $maintainers[0][
                          $subsystems[] |
                          select(
                            . as $subsystem |
                            $changed_file |
                            startswith($subsystem)
                          )
                        ]
                      )[]
                    ] |
                    unique |
                    if length <= $max_maintainers then
                      . | join(",")
                    else
                      ""
                    end
                  '
            )" \
            >>"$GITHUB_OUTPUT"

          echo "$GITHUB_OUTPUT"
