---
# TODO: Rename to 'Request Review' or 'Request Reviewers'.
name: Ping Maintainers

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
# on:
#   push:
#     branches:
#       - master
#   # pull_request:
#   #   types: [opened, ready_for_review, synchronize, reopened, edited]
#   #   paths:
#   #     - 'modules/'

jobs:
  ping-maintainers:
    runs-on: ubuntu-24.04
    if: vars.APP_ID
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: cachix/install-nix-action@v31

      # - uses: cachix/cachix-action@v16
      #   with:
      #     name: stylix
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      #   continue-on-error: true
      #
      # - uses: actions/create-github-app-token@v2
      #   id: app-token
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.APP_PRIVATE_KEY }}
      #     permission-contents: read
      #     permission-pull-requests: write

      - run: nix build .#get-maintainers

      - id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - id: get-maintainers
        env:
          PR_AUTHOR: Flameopathic
        run: |
          MAX_MAINTAINERS=5

          cat "$CHANGED_FILES"
          date
          cat result

          to_ping=()

          jq --raw-output '.[]' <<<"$CHANGED_FILES" | while read -r file; do
            jq --arg file "$file" --raw-output '.[$file][]' result |
              while read -r gh_id;
            do
              to_ping+=("$gh_id")
            done
          done

          if ((${#to_ping[@]} > 0 && ${#to_ping[@]} <= MAX_MAINTAINERS)); then
            printf \
              '%s\n' \
              "::set-output name=to-ping::$(printf '%s,' "${to_ping[@]}")"
          fi

      # - uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     reviewers: ${{ steps.get-maintainers.outputs.to-ping }}
